### PR TITLE
make FlexiRoute demand tracking type-safe

### PR DESCRIPTION
**Pull request by rkuhn**
There is one caveat: in truth our variance annotations on
Source/Flow/Sink which need to be threaded all the way through to InPort
and OutPort are in fact not really correct (actually: inverted) when
writing the “inside” of a stream element, as an InPort behaves as a
source of things and should therefore be covariant. The only point where
this surfaces is the State (in both FlexiMerge/Route) which ties
together the port and element types. In the case of FlexiMerge things
work out by chance because type inference for varargs works covariantly,
“fixing” the wrong contravariance of InPort. For FlexiRoute there is no
such luck, scalac will happily accept all kinds of nonsense code due to
incorrect covariance. The problematic case is DemandFromAny which
demands GLB instead of LUB to be calculated. I fixed this by introducing
a mini-DSL that does this. It works like this:

    val select = p.out0 | p.out1 // will create a set with GLB of both
                                 // types and error out if none exists
    ...
    ctx.emit(select(port))(element)

where `port` is an untyped OutP that is found in the selector set using
object equality. The `port` argument is what the State gives the user,
forcing them to do this kind of resolution (they can also use `if` if
they want). Combine this with DemandFromAll not giving the user any port
info at all (since all of them have demand and can thus nicely be used
directly) and we got all the bases covered—hopefully.

### CODE REVIEW

**Comment by drewhk** [comment]
> There is one caveat: in truth our variance annotations on
Source/Flow/Sink which need to be threaded all the way through to InPort
and OutPort are in fact not really correct (actually: inverted) when
writing the “inside” of a stream element, as an InPort behaves as a
source of things and should therefore be covariant.

Well, this is not really new. The underlying problem is that ports are purely symbolic, and represent actually a covariant or contravariant *position* and not a covariant or contravariant *type*. Every year I have a problem that is caused by this. If I recall correctly once I experimented with something like this:

    InPort[-A, +A] () // disallow direct construction
    def inPort[T](): InPort[T, T] = new ... // set the two parameters to the same type

And where you need different sides of the InPort you use InPort[T, _] or InPort[_, T]. I don't recall how this worked out in the end, but it is ugly anyway :(

**Comment by drewhk** [comment]
@rkuhn, is this still relevant? If so, can you rebase?

**Comment by rkuhn** [comment]
yes, will rebase

**Comment by rkuhn** [comment]
turns out I’m stupid: this was already included in #16 :-)

**Pull request closed without merging**
